version: '2'
services:
    ng2test-app:
        image: ng2test
        external_links:
            - ng2test-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ng2test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ng2test-mysql:
        extends:
            file: mysql.yml
            service: ng2test-mysql
