version: '2'
services:
    ng2test-mysql:
        container_name: ng2test-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/ng2test/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ng2test
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
